<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>Garlic_SaveMgr</AssemblyName>
    <Version>6.8.0</Version>
    <AssemblyVersion>6.8.0.0</AssemblyVersion>
    <FileVersion>6.8.0.0</FileVersion>
    <InformationalVersion>6.8</InformationalVersion>
    <RootNamespace>GarlicSaveMgr</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>garlicon.ico</ApplicationIcon>
    <Platforms>AnyCPU</Platforms>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
    <ItemGroup>
        <Resource Include="garlicon.ico" />
        <Resource Include="garlic-app-icon.png" />
    </ItemGroup>
</Project>
