<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Library</OutputType>
    <AssemblyName>GarlicSaveMgr.TrashModule</AssemblyName>
    <RootNamespace>GarlicSaveMgr.Modules.Trash</RootNamespace>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../GarlicSaveMgr/GarlicSaveMgr.csproj" />
  </ItemGroup>
</Project>
